name: Fetch Google Sheet Data

on:
  schedule:
    - cron: '0 23 */2 * *'  # 23:00 UTC = 6:00 sáng giờ Việt Nam (UTC+7)
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth google-auth-oauthlib google-auth-httplib2 pandas

      - name: Run script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python fetch_sheet_data.py

      - name: Commit updated data
        run: |
          git config --global user.email "hoitkn@msc.masangroup.com"
          git config --global user.name "GitHub Actions"
          git add data.csv
          git commit -m "Update data.csv from Google Sheet" || echo "No changes to commit"
          git push
